#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &



# workspace
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true



# launch programs 

nitrogen --restore &
picom &


$HOME/.config/polybar/launch.sh &

# kills polybar icons - why?
#lxsession &



killall udiskie 
udiskie --tray &

killall keepassxc
keepassxc &

killall mullvad-vpn
mullvad-vpn &


# while bspc node 'any.leaf.!window' -k; do :; done

# rules
bspc rule -a firefox desktop='^2' focus=on follow=on
bspc desktop "^2" -l monocle

bspc rule -a LibreWolf desktop='^3' focus=on follow=on 
bspc desktop "^3" -l monocle

bspc rule -a KeePassXC desktop='^10' focus=on follow=on
bspc desktop "^10" -l monocle

bspc rule -a Steam desktop='^8' focus=on follow=on
bspc rule -a Lutris desktop='^6' focus=on follow=on
bspc rule -a steam_app_782330 desktop='^7' focus=on follow=on

# defaults - leaving them - steven
#   bspc rule -a Gimp desktop='^8' state=floating follow=on
#   bspc rule -a mplayer2 state=floating
#   bspc rule -a Kupfer.py focus=on
#   bspc rule -a Screenkey manage=off
